import { getArchetypeImageUrls } from '@/lib/driveImages'

// Fake profiles for MVP demo — 25 profiles (mixed gender)
// In production, these would come from Firestore
// outfitUrls are populated from Google Drive dummy images at runtime
export const FAKE_PROFILES = [
  // ── 여성 프로필 (15명) ──
  {
    id: 'f1', nickname: '지윤', age: 24, archetypeName: '미니멀 시크걸', archetypeCategory: '미니멀',
    styleTemp: 78, keywords: ['미니멀', '시크', '단정함', '모노톤'],
    colorPalette: ['#1a1a1a', '#4a4a4a', '#8a8a8a', '#d0d0d0'],
    dateMoods: ['미술 전시', '감성 카페', '오마카세', '편집숍'],
    outfitUrls: getArchetypeImageUrls('2'), description: '깔끔한 실루엣에 무채색 톤으로 분위기를 만드는 타입',
  },
  {
    id: 'f2', nickname: '수빈', age: 23, archetypeName: '러블리 페미닌', archetypeCategory: '페미닌',
    styleTemp: 82, keywords: ['페미닌', '핑크', '프릴', '원피스'],
    colorPalette: ['#f5c6d0', '#e8a0b0', '#fff0f3', '#c98a96'],
    dateMoods: ['공원 피크닉', '디저트 카페', '뮤지컬/연극', '플라워 클래스'],
    outfitUrls: getArchetypeImageUrls('24'), description: '사랑스러운 컬러감과 디테일로 여성스러움을 표현하는 스타일',
  },
  {
    id: 'f3', nickname: '하은', age: 25, archetypeName: '프렌치 시크', archetypeCategory: '페미닌',
    styleTemp: 72, keywords: ['프렌치', '에포트리스', '베레모', '스트라이프'],
    colorPalette: ['#2c3e50', '#c0392b', '#ecf0f1', '#f5e6cc'],
    dateMoods: ['북카페', '감성 카페', '사진 전시', '브런치 카페'],
    outfitUrls: getArchetypeImageUrls('26'), description: '힘 안 준 듯한데 세련되어 보이는 파리 감성',
  },
  {
    id: 'f4', nickname: '예린', age: 22, archetypeName: '감성 내추럴', archetypeCategory: '아티스틱',
    styleTemp: 58, keywords: ['어스톤', '내추럴', '오가닉', '차분함'],
    colorPalette: ['#8b7355', '#c4a882', '#e8dcc8', '#5c4a32'],
    dateMoods: ['도예 체험', '북카페', '캠핑', '한강 산책'],
    outfitUrls: getArchetypeImageUrls('20'), description: '자연스럽고 차분한 톤의 편안한 감성파',
  },
  {
    id: 'f5', nickname: '민서', age: 26, archetypeName: '걸크러시 시크', archetypeCategory: '페미닌',
    styleTemp: 85, keywords: ['걸크러시', '파워풀', '모던', '숏컷'],
    colorPalette: ['#0d0d0d', '#333333', '#b0b0b0', '#ff4444'],
    dateMoods: ['칵테일바', '편집숍', '콘서트', '팝업스토어'],
    outfitUrls: getArchetypeImageUrls('25'), description: '쿨하고 강한 무드의 자신감 넘치는 스타일',
  },
  {
    id: 'f6', nickname: '서아', age: 24, archetypeName: '클린 베이직', archetypeCategory: '미니멀',
    styleTemp: 55, keywords: ['베이직', '깔끔', '무난', '데일리'],
    colorPalette: ['#ffffff', '#e0e0e0', '#a0a0a0', '#4a6fa5'],
    dateMoods: ['영화관', '한강 산책', '맛집 탐방', '브런치 카페'],
    outfitUrls: getArchetypeImageUrls('3'), description: '기본에 충실하지만 깔끔한 느낌이 좋은 타입',
  },
  {
    id: 'f7', nickname: '다현', age: 23, archetypeName: '빈티지 로맨틱', archetypeCategory: '아티스틱',
    styleTemp: 76, keywords: ['빈티지', '레트로', '플로럴', '레이스'],
    colorPalette: ['#8b4513', '#deb887', '#f0e68c', '#cd853f'],
    dateMoods: ['빈티지숍', '도예 체험', '공원 피크닉', '사진 전시'],
    outfitUrls: getArchetypeImageUrls('21'), description: '과거 감성을 오늘 스타일로 소화하는 빈티지 감각',
  },
  {
    id: 'f8', nickname: '채원', age: 25, archetypeName: '코지 무드', archetypeCategory: '캐주얼',
    styleTemp: 48, keywords: ['니트', '따뜻함', '라운지', '오버핏'],
    colorPalette: ['#d4a574', '#f5e6d3', '#a0785a', '#ffe4c4'],
    dateMoods: ['보드게임 카페', '영화관', '도예 체험', '한강 산책'],
    outfitUrls: getArchetypeImageUrls('8'), description: '포근하고 따뜻한 무드의 편안한 스타일',
  },
  {
    id: 'f9', nickname: '윤아', age: 27, archetypeName: '소프트 클래식', archetypeCategory: '클래식',
    styleTemp: 73, keywords: ['클래식', '부드러움', '뉴트럴', '여성스러움'],
    colorPalette: ['#c9b99a', '#e8dcc8', '#8b7355', '#f5f0eb'],
    dateMoods: ['뮤지컬/연극', '오마카세', '와인바', '공원 피크닉'],
    outfitUrls: getArchetypeImageUrls('16'), description: '우아하고 부드러운 클래식 감성의 소유자',
  },
  {
    id: 'f10', nickname: '시은', age: 22, archetypeName: '스포티 프레시', archetypeCategory: '캐주얼',
    styleTemp: 52, keywords: ['스포츠믹스', '활동적', '컬러풀', '에너지'],
    colorPalette: ['#ff6b35', '#1a73e8', '#ffffff', '#2d2d2d'],
    dateMoods: ['한강 산책', '맛집 탐방', '드라이브', '보드게임 카페'],
    outfitUrls: getArchetypeImageUrls('7'), description: '에너지 넘치고 밝은 스포티 감성',
  },
  {
    id: 'f11', nickname: '지수', age: 26, archetypeName: '모노톤 무드', archetypeCategory: '미니멀',
    styleTemp: 70, keywords: ['블랙&화이트', '무채색', '절제', '심플'],
    colorPalette: ['#000000', '#333333', '#999999', '#ffffff'],
    dateMoods: ['미술 전시', '감성 카페', '루프탑 바', '편집숍'],
    outfitUrls: getArchetypeImageUrls('4'), description: '무채색만으로도 확실한 존재감을 보여주는 타입',
  },
  {
    id: 'f12', nickname: '은서', age: 24, archetypeName: '뉴트로 무드', archetypeCategory: '아티스틱',
    styleTemp: 67, keywords: ['레트로', '컬러', '올드스쿨', '믹스매치'],
    colorPalette: ['#e07b39', '#2e5090', '#e8d44d', '#3a7d44'],
    dateMoods: ['빈티지숍', '팝업스토어', '독립영화관', '맛집 탐방'],
    outfitUrls: getArchetypeImageUrls('22'), description: '복고를 힙하게 해석하는 뉴트로 감각',
  },
  {
    id: 'f13', nickname: '소율', age: 23, archetypeName: '캠퍼스 프레피', archetypeCategory: '캐주얼',
    styleTemp: 62, keywords: ['캠퍼스', '프레피', '니트조끼', '체크'],
    colorPalette: ['#1b4332', '#f2e8cf', '#bc6c25', '#606c38'],
    dateMoods: ['북카페', '한강 산책', '브런치 카페', '보드게임 카페'],
    outfitUrls: getArchetypeImageUrls('10'), description: '깔끔한 캠퍼스 무드의 프레피 스타일',
  },
  {
    id: 'f14', nickname: '유나', age: 25, archetypeName: '글램 맥시멀', archetypeCategory: '맥시멀',
    styleTemp: 94, keywords: ['화려함', '악세서리', '패턴', '볼드컬러'],
    colorPalette: ['#c9184a', '#ffb703', '#8338ec', '#06d6a0'],
    dateMoods: ['파인다이닝', '콘서트', '칵테일바', '팝업스토어'],
    outfitUrls: getArchetypeImageUrls('27'), description: '화려하고 존재감 있는 글램 스타일의 정점',
  },
  {
    id: 'f15', nickname: '하린', age: 22, archetypeName: '릴렉스 캐주얼', archetypeCategory: '캐주얼',
    styleTemp: 45, keywords: ['캐주얼', '편안함', '자연스러움', '데일리'],
    colorPalette: ['#6b705c', '#a5a58d', '#b6ad90', '#ddbea9'],
    dateMoods: ['영화관', '한강 산책', '맛집 탐방', '캠핑'],
    outfitUrls: getArchetypeImageUrls('6'), description: '힘 빼고 자연스러운 일상의 편안함',
  },

  // ── 남성 프로필 (10명) ──
  {
    id: 'm1', nickname: '준혁', age: 25, archetypeName: '미니멀 시티보이', archetypeCategory: '미니멀',
    styleTemp: 80, keywords: ['미니멀', '모던캐주얼', '깔끔', '시티무드'],
    colorPalette: ['#1c1c1c', '#3d3d3d', '#7a7a7a', '#c8c8c8'],
    dateMoods: ['감성 카페', '사진 전시', '드라이브', '루프탑 바'],
    outfitUrls: getArchetypeImageUrls('1'), description: '도시적 감성의 정돈된 스타일',
  },
  {
    id: 'm2', nickname: '도윤', age: 24, archetypeName: '어반 스트릿', archetypeCategory: '스트릿',
    styleTemp: 68, keywords: ['스트릿', '오버핏', '그래픽', '하이탑'],
    colorPalette: ['#1a1a1a', '#555555', '#e74c3c', '#ffffff'],
    dateMoods: ['콘서트', '팝업스토어', '맛집 탐방', '드라이브'],
    outfitUrls: getArchetypeImageUrls('11'), description: '스트릿 감성으로 도시를 누비는 타입',
  },
  {
    id: 'm3', nickname: '시우', age: 23, archetypeName: '모던 클래식', archetypeCategory: '클래식',
    styleTemp: 78, keywords: ['클래식', '단정함', '셔츠', '슬랙스'],
    colorPalette: ['#2c3e50', '#34495e', '#bdc3c7', '#ecf0f1'],
    dateMoods: ['와인바', '재즈바', '오마카세', '루프탑 바'],
    outfitUrls: getArchetypeImageUrls('15'), description: '클래식을 현대적으로 소화하는 댄디한 매력',
  },
  {
    id: 'm4', nickname: '하준', age: 26, archetypeName: '릴렉스 캐주얼', archetypeCategory: '캐주얼',
    styleTemp: 45, keywords: ['캐주얼', '편안함', '자연스러움', '데일리'],
    colorPalette: ['#5d6d7e', '#aeb6bf', '#d5d8dc', '#f2f3f4'],
    dateMoods: ['영화관', '한강 산책', '맛집 탐방', '보드게임 카페'],
    outfitUrls: getArchetypeImageUrls('6'), description: '편안하고 자연스러운 데일리 룩의 정석',
  },
  {
    id: 'm5', nickname: '건우', age: 27, archetypeName: '아메카지 무드', archetypeCategory: '맥시멀',
    styleTemp: 70, keywords: ['워크웨어', '빈티지', '내추럴', '레이어드'],
    colorPalette: ['#5c4033', '#8b6914', '#c19a6b', '#36454f'],
    dateMoods: ['캠핑', '빈티지숍', '맛집 탐방', '드라이브'],
    outfitUrls: getArchetypeImageUrls('29'), description: '워크웨어 기반의 멋스러운 레이어드 마니아',
  },
  {
    id: 'm6', nickname: '현우', age: 24, archetypeName: '하이엔드 스트릿', archetypeCategory: '스트릿',
    styleTemp: 88, keywords: ['럭셔리스트릿', '브랜드믹스', '볼드', '트렌드'],
    colorPalette: ['#0d0d0d', '#2d2d2d', '#c8ff00', '#ff4500'],
    dateMoods: ['팝업스토어', '칵테일바', '콘서트', '편집숍'],
    outfitUrls: getArchetypeImageUrls('12'), description: '럭셔리와 스트릿을 자유자재로 믹스하는 스타일',
  },
  {
    id: 'm7', nickname: '지호', age: 23, archetypeName: '클린 베이직', archetypeCategory: '미니멀',
    styleTemp: 52, keywords: ['베이직', '깔끔', '무난', '데일리'],
    colorPalette: ['#ffffff', '#d0d0d0', '#808080', '#2f4f4f'],
    dateMoods: ['영화관', '한강 산책', '브런치 카페', '보드게임 카페'],
    outfitUrls: getArchetypeImageUrls('3'), description: '기본기가 탄탄한 깔끔한 스타일',
  },
  {
    id: 'm8', nickname: '서진', age: 25, archetypeName: '다크 아티스틱', archetypeCategory: '아티스틱',
    styleTemp: 90, keywords: ['블랙', '아방가르드', '질감', '실루엣'],
    colorPalette: ['#0a0a0a', '#1a1a1a', '#2d2d2d', '#4a4a4a'],
    dateMoods: ['미술 전시', '와인바', '향수 만들기', '독립영화관'],
    outfitUrls: getArchetypeImageUrls('19'), description: '올블랙으로 자신만의 세계관을 구축하는 타입',
  },
  {
    id: 'm9', nickname: '태현', age: 26, archetypeName: '댄디 포멀', archetypeCategory: '클래식',
    styleTemp: 92, keywords: ['포멀', '수트', '정장감', '세련됨'],
    colorPalette: ['#1b2631', '#2c3e50', '#85929e', '#d5d8dc'],
    dateMoods: ['파인다이닝', '재즈바', '루프탑 바', '뮤지컬/연극'],
    outfitUrls: getArchetypeImageUrls('17'), description: '수트가 가장 잘 어울리는 클래식 포멀의 정석',
  },
  {
    id: 'm10', nickname: '우진', age: 22, archetypeName: '스포티 프레시', archetypeCategory: '캐주얼',
    styleTemp: 50, keywords: ['스포츠믹스', '활동적', '컬러풀', '에너지'],
    colorPalette: ['#1e90ff', '#ffffff', '#ff4500', '#2d2d2d'],
    dateMoods: ['한강 산책', '드라이브', '맛집 탐방', '보드게임 카페'],
    outfitUrls: getArchetypeImageUrls('7'), description: '활력 넘치는 스포티한 프레시 감성',
  },
]
