import type { Archetype, DateMood } from '@/types/style'

export const ARCHETYPES: Archetype[] = [
  { id: '1', category: '미니멀', gender: 'M', name: '미니멀 시티보이', keywords: ['미니멀', '모던캐주얼', '깔끔', '시티무드'], tempRange: { min: 70, max: 85 }, description: '도시적이고 정돈된 무드의 깔끔남' },
  { id: '2', category: '미니멀', gender: 'F', name: '미니멀 시크걸', keywords: ['미니멀', '시크', '단정함', '모노톤'], tempRange: { min: 70, max: 85 }, description: '군더더기 없는 세련된 무드' },
  { id: '3', category: '미니멀', gender: 'U', name: '클린 베이직', keywords: ['베이직', '깔끔', '무난', '데일리'], tempRange: { min: 50, max: 65 }, description: '기본에 충실한 깨끗한 스타일' },
  { id: '4', category: '미니멀', gender: 'U', name: '모노톤 무드', keywords: ['블랙&화이트', '무채색', '절제', '심플'], tempRange: { min: 65, max: 80 }, description: '컬러 없이도 분위기가 있는 타입' },
  { id: '5', category: '미니멀', gender: 'U', name: '쿨톤 미니멀', keywords: ['블루그레이', '차가운톤', '슬림핏', '절제미'], tempRange: { min: 70, max: 80 }, description: '쿨한 색감으로 정리된 스타일' },
  { id: '6', category: '캐주얼', gender: 'U', name: '릴렉스 캐주얼', keywords: ['캐주얼', '편안함', '자연스러움', '데일리'], tempRange: { min: 40, max: 55 }, description: '힘 빼고 자연스러운 일상 스타일' },
  { id: '7', category: '캐주얼', gender: 'U', name: '스포티 프레시', keywords: ['스포츠믹스', '활동적', '컬러풀', '에너지'], tempRange: { min: 45, max: 60 }, description: '활동적이고 밝은 에너지 스타일' },
  { id: '8', category: '캐주얼', gender: 'U', name: '코지 무드', keywords: ['니트', '따뜻함', '라운지', '오버핏'], tempRange: { min: 40, max: 55 }, description: '따뜻하고 포근한 집순이/집돌이 무드' },
  { id: '9', category: '캐주얼', gender: 'U', name: '서프 캐주얼', keywords: ['서핑', '리조트', '여유로움', '썸머바이브'], tempRange: { min: 35, max: 50 }, description: '바다 느낌 나는 자유로운 스타일' },
  { id: '10', category: '캐주얼', gender: 'U', name: '캠퍼스 프레피', keywords: ['캠퍼스', '프레피', '니트조끼', '체크'], tempRange: { min: 55, max: 70 }, description: '학교 다닐 때 느낌의 깔끔 캐주얼' },
  { id: '11', category: '스트릿', gender: 'U', name: '어반 스트릿', keywords: ['스트릿', '오버핏', '그래픽', '하이탑'], tempRange: { min: 60, max: 75 }, description: '도시형 스트릿 감성' },
  { id: '12', category: '스트릿', gender: 'U', name: '하이엔드 스트릿', keywords: ['럭셔리스트릿', '브랜드믹스', '볼드', '트렌드'], tempRange: { min: 80, max: 95 }, description: '브랜드와 스트릿의 하이브리드' },
  { id: '13', category: '스트릿', gender: 'U', name: '테크웨어 무드', keywords: ['테크웨어', '기능성', '올블랙', '미래적'], tempRange: { min: 75, max: 90 }, description: '기능적이고 미래지향적 스타일' },
  { id: '14', category: '스트릿', gender: 'U', name: '스케이터 바이브', keywords: ['스케이트', '루즈핏', '그런지', '로고'], tempRange: { min: 50, max: 65 }, description: '스케이트보드 감성의 자유로운 룩' },
  { id: '15', category: '클래식', gender: 'U', name: '모던 클래식', keywords: ['클래식', '단정함', '셔츠', '슬랙스'], tempRange: { min: 70, max: 85 }, description: '현대적으로 재해석한 클래식' },
  { id: '16', category: '클래식', gender: 'U', name: '소프트 클래식', keywords: ['클래식', '부드러움', '뉴트럴', '여성스러움'], tempRange: { min: 65, max: 80 }, description: '부드럽고 우아한 클래식 감성' },
  { id: '17', category: '클래식', gender: 'U', name: '댄디 포멀', keywords: ['포멀', '수트', '정장감', '세련됨'], tempRange: { min: 85, max: 95 }, description: '정장에서 존재감이 나는 타입' },
  { id: '18', category: '클래식', gender: 'U', name: '비즈캐주얼 무드', keywords: ['비즈캐주얼', '오피스룩', '깔끔', '신뢰감'], tempRange: { min: 65, max: 80 }, description: '일할 때도 센스 있는 스타일' },
  { id: '19', category: '아티스틱', gender: 'U', name: '다크 아티스틱', keywords: ['블랙', '아방가르드', '질감', '실루엣'], tempRange: { min: 85, max: 95 }, description: '블랙과 질감으로 세계관을 만드는 타입' },
  { id: '20', category: '아티스틱', gender: 'U', name: '감성 내추럴', keywords: ['어스톤', '내추럴', '오가닉', '차분함'], tempRange: { min: 50, max: 65 }, description: '자연스럽고 차분한 감성파' },
  { id: '21', category: '아티스틱', gender: 'U', name: '빈티지 로맨틱', keywords: ['빈티지', '레트로', '플로럴', '레이스'], tempRange: { min: 70, max: 85 }, description: '과거 감성을 현대적으로 입는 스타일' },
  { id: '22', category: '아티스틱', gender: 'U', name: '뉴트로 무드', keywords: ['레트로', '컬러', '올드스쿨', '믹스매치'], tempRange: { min: 60, max: 75 }, description: '복고를 새롭게 해석하는 감각' },
  { id: '23', category: '아티스틱', gender: 'U', name: '유니크 크리에이터', keywords: ['실험적', '젠더리스', '믹스매치', '개성'], tempRange: { min: 85, max: 100 }, description: '규칙 없이 자기만의 룩을 만드는 타입' },
  { id: '24', category: '페미닌', gender: 'F', name: '러블리 페미닌', keywords: ['페미닌', '핑크', '프릴', '원피스'], tempRange: { min: 70, max: 85 }, description: '사랑스럽고 여성스러운 무드' },
  { id: '25', category: '페미닌', gender: 'F', name: '걸크러시 시크', keywords: ['걸크러시', '파워풀', '모던', '숏컷'], tempRange: { min: 75, max: 90 }, description: '쿨하고 힘 있는 여성 스타일' },
  { id: '26', category: '페미닌', gender: 'U', name: '프렌치 시크', keywords: ['프렌치', '에포트리스', '베레모', '스트라이프'], tempRange: { min: 65, max: 80 }, description: '힘 안 준 듯 세련된 파리지엔 무드' },
  { id: '27', category: '맥시멀', gender: 'U', name: '글램 맥시멀', keywords: ['화려함', '악세서리', '패턴', '볼드컬러'], tempRange: { min: 90, max: 100 }, description: '확실하게 꾸미고 존재감 있는 스타일' },
  { id: '28', category: '맥시멀', gender: 'U', name: '보헤미안 프리', keywords: ['보헤미안', '자유로움', '패턴믹스', '액세서리'], tempRange: { min: 70, max: 85 }, description: '자유롭고 이국적인 히피 감성' },
  { id: '29', category: '맥시멀', gender: 'U', name: '아메카지 무드', keywords: ['워크웨어', '빈티지', '내추럴', '레이어드'], tempRange: { min: 60, max: 75 }, description: '워크웨어 기반 레이어드 마니아' },
  { id: '30', category: '맥시멀', gender: 'U', name: '컬러팝 무드', keywords: ['비비드', '컬러블록', '대담', '펀'], tempRange: { min: 70, max: 85 }, description: '색감으로 승부하는 밝은 에너지' },
]

export const DATE_MOODS: DateMood[] = [
  // 감상/문화 (15)
  { id: '1', name: '미술 전시', icon: '🖼', category: '감상/문화', matchingArchetypes: ['다크 아티스틱', '감성 내추럴', '미니멀 시크걸'] },
  { id: '2', name: '사진 전시', icon: '📷', category: '감상/문화', matchingArchetypes: ['미니멀 시티보이', '감성 내추럴', '프렌치 시크'] },
  { id: '3', name: '뮤지컬/연극', icon: '🎭', category: '감상/문화', matchingArchetypes: ['댄디 포멀', '소프트 클래식', '러블리 페미닌'] },
  { id: '4', name: '콘서트', icon: '🎸', category: '감상/문화', matchingArchetypes: ['어반 스트릿', '하이엔드 스트릿', '글램 맥시멀'] },
  { id: '5', name: '재즈바', icon: '🎷', category: '감상/문화', matchingArchetypes: ['모던 클래식', '댄디 포멀', '다크 아티스틱'] },
  { id: '6', name: '영화관', icon: '🎬', category: '감상/문화', matchingArchetypes: ['릴렉스 캐주얼', '코지 무드', '클린 베이직'] },
  { id: '7', name: '독립영화관', icon: '🎞', category: '감상/문화', matchingArchetypes: ['감성 내추럴', '다크 아티스틱', '뉴트로 무드'] },
  { id: '8', name: '북카페', icon: '📖', category: '감상/문화', matchingArchetypes: ['감성 내추럴', '미니멀 시티보이', '프렌치 시크'] },
  { id: '9', name: '서점 나들이', icon: '📚', category: '감상/문화', matchingArchetypes: ['클린 베이직', '감성 내추럴', '소프트 클래식'] },
  { id: '10', name: '뮤지엄', icon: '🏛', category: '감상/문화', matchingArchetypes: ['미니멀 시티보이', '모던 클래식', '캠퍼스 프레피'] },
  { id: '11', name: '팝업 전시', icon: '🎨', category: '감상/문화', matchingArchetypes: ['하이엔드 스트릿', '유니크 크리에이터', '어반 스트릿'] },
  { id: '12', name: '버스킹 구경', icon: '🎤', category: '감상/문화', matchingArchetypes: ['릴렉스 캐주얼', '뉴트로 무드', '보헤미안 프리'] },
  { id: '13', name: '페스티벌', icon: '🎪', category: '감상/문화', matchingArchetypes: ['글램 맥시멀', '보헤미안 프리', '스포티 프레시'] },
  { id: '14', name: '강연/토크쇼', icon: '🎙', category: '감상/문화', matchingArchetypes: ['비즈캐주얼 무드', '모던 클래식', '감성 내추럴'] },
  { id: '15', name: '원데이 클래스', icon: '✂️', category: '감상/문화', matchingArchetypes: ['감성 내추럴', '러블리 페미닌', '빈티지 로맨틱'] },

  // 카페/음료 (12)
  { id: '16', name: '감성 카페', icon: '☕', category: '카페/음료', matchingArchetypes: ['미니멀 시크걸', '프렌치 시크', '러블리 페미닌'] },
  { id: '17', name: '로스터리 카페', icon: '☕', category: '카페/음료', matchingArchetypes: ['미니멀 시티보이', '클린 베이직', '감성 내추럴'] },
  { id: '18', name: '디저트 카페', icon: '🍰', category: '카페/음료', matchingArchetypes: ['러블리 페미닌', '코지 무드', '소프트 클래식'] },
  { id: '19', name: '와인바', icon: '🍷', category: '카페/음료', matchingArchetypes: ['다크 아티스틱', '모던 클래식', '댄디 포멀'] },
  { id: '20', name: '칵테일바', icon: '🍸', category: '카페/음료', matchingArchetypes: ['하이엔드 스트릿', '글램 맥시멀', '걸크러시 시크'] },
  { id: '21', name: '위스키바', icon: '🥃', category: '카페/음료', matchingArchetypes: ['모던 클래식', '댄디 포멀', '아메카지 무드'] },
  { id: '22', name: '루프탑 바', icon: '🌃', category: '카페/음료', matchingArchetypes: ['미니멀 시티보이', '댄디 포멀', '모던 클래식'] },
  { id: '23', name: '전통 찻집', icon: '🍵', category: '카페/음료', matchingArchetypes: ['감성 내추럴', '소프트 클래식', '빈티지 로맨틱'] },
  { id: '24', name: '브런치 카페', icon: '🥐', category: '카페/음료', matchingArchetypes: ['프렌치 시크', '클린 베이직', '캠퍼스 프레피'] },
  { id: '25', name: '펍', icon: '🍺', category: '카페/음료', matchingArchetypes: ['아메카지 무드', '어반 스트릿', '스케이터 바이브'] },
  { id: '26', name: '소주바/이자카야', icon: '🍶', category: '카페/음료', matchingArchetypes: ['뉴트로 무드', '릴렉스 캐주얼', '아메카지 무드'] },
  { id: '27', name: '논알콜 바', icon: '🧃', category: '카페/음료', matchingArchetypes: ['클린 베이직', '코지 무드', '감성 내추럴'] },

  // 식사 (12)
  { id: '28', name: '파인다이닝', icon: '🍽', category: '식사', matchingArchetypes: ['댄디 포멀', '글램 맥시멀', '모던 클래식'] },
  { id: '29', name: '오마카세', icon: '🍣', category: '식사', matchingArchetypes: ['미니멀 시크걸', '모던 클래식', '다크 아티스틱'] },
  { id: '30', name: '조용한 레스토랑', icon: '🕯', category: '식사', matchingArchetypes: ['소프트 클래식', '미니멀 시크걸', '프렌치 시크'] },
  { id: '31', name: '맛집 탐방', icon: '🍜', category: '식사', matchingArchetypes: ['릴렉스 캐주얼', '스포티 프레시', '어반 스트릿'] },
  { id: '32', name: '이색 요리 체험', icon: '🧑‍🍳', category: '식사', matchingArchetypes: ['감성 내추럴', '러블리 페미닌', '뉴트로 무드'] },
  { id: '33', name: '포장마차/야시장', icon: '🏮', category: '식사', matchingArchetypes: ['뉴트로 무드', '릴렉스 캐주얼', '스케이터 바이브'] },
  { id: '34', name: '한정식', icon: '🍚', category: '식사', matchingArchetypes: ['소프트 클래식', '감성 내추럴', '모던 클래식'] },
  { id: '35', name: '해산물 레스토랑', icon: '🦞', category: '식사', matchingArchetypes: ['서프 캐주얼', '릴렉스 캐주얼', '모던 클래식'] },
  { id: '36', name: '비건/건강식', icon: '🥗', category: '식사', matchingArchetypes: ['감성 내추럴', '클린 베이직', '쿨톤 미니멀'] },
  { id: '37', name: '루프탑 레스토랑', icon: '🌇', category: '식사', matchingArchetypes: ['댄디 포멀', '글램 맥시멀', '미니멀 시티보이'] },
  { id: '38', name: '브런치 맛집', icon: '🥞', category: '식사', matchingArchetypes: ['프렌치 시크', '러블리 페미닌', '캠퍼스 프레피'] },
  { id: '39', name: '딤섬/중식', icon: '🥟', category: '식사', matchingArchetypes: ['어반 스트릿', '릴렉스 캐주얼', '뉴트로 무드'] },

  // 야외/자연 (15)
  { id: '40', name: '한강 산책', icon: '🌊', category: '야외/자연', matchingArchetypes: ['릴렉스 캐주얼', '클린 베이직', '스포티 프레시'] },
  { id: '41', name: '공원 피크닉', icon: '🧺', category: '야외/자연', matchingArchetypes: ['러블리 페미닌', '빈티지 로맨틱', '코지 무드'] },
  { id: '42', name: '드라이브', icon: '🚗', category: '야외/자연', matchingArchetypes: ['미니멀 시티보이', '모던 클래식', '어반 스트릿'] },
  { id: '43', name: '등산/트레킹', icon: '🥾', category: '야외/자연', matchingArchetypes: ['스포티 프레시', '아메카지 무드', '감성 내추럴'] },
  { id: '44', name: '자전거 라이딩', icon: '🚴', category: '야외/자연', matchingArchetypes: ['스포티 프레시', '릴렉스 캐주얼', '서프 캐주얼'] },
  { id: '45', name: '바다/해변', icon: '🏖', category: '야외/자연', matchingArchetypes: ['서프 캐주얼', '보헤미안 프리', '스포티 프레시'] },
  { id: '46', name: '캠핑', icon: '⛺', category: '야외/자연', matchingArchetypes: ['아메카지 무드', '릴렉스 캐주얼', '감성 내추럴'] },
  { id: '47', name: '꽃구경/식물원', icon: '🌷', category: '야외/자연', matchingArchetypes: ['감성 내추럴', '러블리 페미닌', '소프트 클래식'] },
  { id: '48', name: '야경 명소', icon: '🌙', category: '야외/자연', matchingArchetypes: ['미니멀 시티보이', '댄디 포멀', '다크 아티스틱'] },
  { id: '49', name: '일출/일몰', icon: '🌅', category: '야외/자연', matchingArchetypes: ['감성 내추럴', '보헤미안 프리', '코지 무드'] },
  { id: '50', name: '테마파크', icon: '🎢', category: '야외/자연', matchingArchetypes: ['스포티 프레시', '릴렉스 캐주얼', '컬러팝 무드'] },
  { id: '51', name: '동물원/아쿠아리움', icon: '🐧', category: '야외/자연', matchingArchetypes: ['코지 무드', '러블리 페미닌', '캠퍼스 프레피'] },
  { id: '52', name: '카약/수상스포츠', icon: '🛶', category: '야외/자연', matchingArchetypes: ['스포티 프레시', '서프 캐주얼', '릴렉스 캐주얼'] },
  { id: '53', name: '스키/보드', icon: '🏂', category: '야외/자연', matchingArchetypes: ['스포티 프레시', '테크웨어 무드', '어반 스트릿'] },
  { id: '54', name: '골프/스크린골프', icon: '⛳', category: '야외/자연', matchingArchetypes: ['비즈캐주얼 무드', '모던 클래식', '캠퍼스 프레피'] },

  // 쇼핑/탐방 (13)
  { id: '55', name: '편집숍', icon: '🛍', category: '쇼핑/탐방', matchingArchetypes: ['미니멀 시크걸', '하이엔드 스트릿', '다크 아티스틱'] },
  { id: '56', name: '빈티지숍', icon: '👗', category: '쇼핑/탐방', matchingArchetypes: ['빈티지 로맨틱', '아메카지 무드', '뉴트로 무드'] },
  { id: '57', name: '플리마켓', icon: '🧵', category: '쇼핑/탐방', matchingArchetypes: ['보헤미안 프리', '감성 내추럴', '빈티지 로맨틱'] },
  { id: '58', name: '팝업스토어', icon: '🏪', category: '쇼핑/탐방', matchingArchetypes: ['하이엔드 스트릿', '유니크 크리에이터', '어반 스트릿'] },
  { id: '59', name: '백화점 쇼핑', icon: '🏬', category: '쇼핑/탐방', matchingArchetypes: ['댄디 포멀', '글램 맥시멀', '모던 클래식'] },
  { id: '60', name: '성수/한남 탐방', icon: '🚶', category: '쇼핑/탐방', matchingArchetypes: ['미니멀 시티보이', '하이엔드 스트릿', '프렌치 시크'] },
  { id: '61', name: '전통시장', icon: '🏮', category: '쇼핑/탐방', matchingArchetypes: ['뉴트로 무드', '릴렉스 캐주얼', '아메카지 무드'] },
  { id: '62', name: '인테리어 숍', icon: '🪑', category: '쇼핑/탐방', matchingArchetypes: ['감성 내추럴', '미니멀 시크걸', '모노톤 무드'] },
  { id: '63', name: '레코드샵', icon: '💿', category: '쇼핑/탐방', matchingArchetypes: ['뉴트로 무드', '다크 아티스틱', '아메카지 무드'] },
  { id: '64', name: '식물/꽃집', icon: '🌿', category: '쇼핑/탐방', matchingArchetypes: ['감성 내추럴', '러블리 페미닌', '보헤미안 프리'] },
  { id: '65', name: '향수 매장', icon: '🌸', category: '쇼핑/탐방', matchingArchetypes: ['다크 아티스틱', '미니멀 시크걸', '프렌치 시크'] },
  { id: '66', name: '문구점/아트숍', icon: '🖊', category: '쇼핑/탐방', matchingArchetypes: ['감성 내추럴', '캠퍼스 프레피', '빈티지 로맨틱'] },
  { id: '67', name: '한옥마을 산책', icon: '🏯', category: '쇼핑/탐방', matchingArchetypes: ['소프트 클래식', '감성 내추럴', '프렌치 시크'] },

  // 실내 활동 (15)
  { id: '68', name: '보드게임 카페', icon: '🎲', category: '실내 활동', matchingArchetypes: ['코지 무드', '릴렉스 캐주얼', '뉴트로 무드'] },
  { id: '69', name: '방탈출', icon: '🔐', category: '실내 활동', matchingArchetypes: ['어반 스트릿', '스포티 프레시', '테크웨어 무드'] },
  { id: '70', name: '볼링/당구', icon: '🎳', category: '실내 활동', matchingArchetypes: ['릴렉스 캐주얼', '스포티 프레시', '어반 스트릿'] },
  { id: '71', name: '노래방', icon: '🎤', category: '실내 활동', matchingArchetypes: ['릴렉스 캐주얼', '글램 맥시멀', '뉴트로 무드'] },
  { id: '72', name: 'VR체험', icon: '🥽', category: '실내 활동', matchingArchetypes: ['테크웨어 무드', '스포티 프레시', '어반 스트릿'] },
  { id: '73', name: '스파/찜질방', icon: '♨️', category: '실내 활동', matchingArchetypes: ['코지 무드', '릴렉스 캐주얼', '감성 내추럴'] },
  { id: '74', name: '요가/필라테스', icon: '🧘', category: '실내 활동', matchingArchetypes: ['감성 내추럴', '클린 베이직', '쿨톤 미니멀'] },
  { id: '75', name: '실내 클라이밍', icon: '🧗', category: '실내 활동', matchingArchetypes: ['스포티 프레시', '테크웨어 무드', '어반 스트릿'] },
  { id: '76', name: '게임/PC방', icon: '🎮', category: '실내 활동', matchingArchetypes: ['릴렉스 캐주얼', '스케이터 바이브', '코지 무드'] },
  { id: '77', name: '다트/포켓볼', icon: '🎯', category: '실내 활동', matchingArchetypes: ['아메카지 무드', '어반 스트릿', '모던 클래식'] },
  { id: '78', name: '수영', icon: '🏊', category: '실내 활동', matchingArchetypes: ['스포티 프레시', '서프 캐주얼', '클린 베이직'] },
  { id: '79', name: '아이스링크', icon: '⛸', category: '실내 활동', matchingArchetypes: ['러블리 페미닌', '스포티 프레시', '캠퍼스 프레피'] },
  { id: '80', name: '탁구', icon: '🏓', category: '실내 활동', matchingArchetypes: ['릴렉스 캐주얼', '스포티 프레시', '뉴트로 무드'] },
  { id: '81', name: '사격/양궁체험', icon: '🏹', category: '실내 활동', matchingArchetypes: ['테크웨어 무드', '어반 스트릿', '스포티 프레시'] },
  { id: '82', name: '만화카페', icon: '📖', category: '실내 활동', matchingArchetypes: ['코지 무드', '뉴트로 무드', '릴렉스 캐주얼'] },

  // 체험/창작 (10)
  { id: '83', name: '도예 체험', icon: '🏺', category: '체험/창작', matchingArchetypes: ['감성 내추럴', '빈티지 로맨틱', '코지 무드'] },
  { id: '84', name: '향수 만들기', icon: '🌸', category: '체험/창작', matchingArchetypes: ['다크 아티스틱', '미니멀 시크걸', '프렌치 시크'] },
  { id: '85', name: '캔들 만들기', icon: '🕯', category: '체험/창작', matchingArchetypes: ['러블리 페미닌', '코지 무드', '감성 내추럴'] },
  { id: '86', name: '가죽 공예', icon: '🧳', category: '체험/창작', matchingArchetypes: ['아메카지 무드', '모던 클래식', '다크 아티스틱'] },
  { id: '87', name: '드로잉/페인팅', icon: '🎨', category: '체험/창작', matchingArchetypes: ['유니크 크리에이터', '감성 내추럴', '빈티지 로맨틱'] },
  { id: '88', name: '플라워 클래스', icon: '💐', category: '체험/창작', matchingArchetypes: ['러블리 페미닌', '소프트 클래식', '감성 내추럴'] },
  { id: '89', name: '사진 촬영', icon: '📸', category: '체험/창작', matchingArchetypes: ['뉴트로 무드', '미니멀 시티보이', '프렌치 시크'] },
  { id: '90', name: '목공 체험', icon: '🪵', category: '체험/창작', matchingArchetypes: ['아메카지 무드', '감성 내추럴', '클린 베이직'] },
  { id: '91', name: '베이킹 클래스', icon: '🧁', category: '체험/창작', matchingArchetypes: ['코지 무드', '러블리 페미닌', '캠퍼스 프레피'] },
  { id: '92', name: '실크스크린 체험', icon: '🖼', category: '체험/창작', matchingArchetypes: ['유니크 크리에이터', '어반 스트릿', '뉴트로 무드'] },

  // 나이트/특별 (8)
  { id: '93', name: '클럽/파티', icon: '🪩', category: '나이트/특별', matchingArchetypes: ['글램 맥시멀', '하이엔드 스트릿', '유니크 크리에이터'] },
  { id: '94', name: '라운지 바', icon: '🛋', category: '나이트/특별', matchingArchetypes: ['댄디 포멀', '모던 클래식', '미니멀 시크걸'] },
  { id: '95', name: '포차/노포', icon: '🏮', category: '나이트/특별', matchingArchetypes: ['뉴트로 무드', '릴렉스 캐주얼', '아메카지 무드'] },
  { id: '96', name: '야시장/나이트마켓', icon: '🌙', category: '나이트/특별', matchingArchetypes: ['보헤미안 프리', '뉴트로 무드', '어반 스트릿'] },
  { id: '97', name: '스카이라운지', icon: '🏙', category: '나이트/특별', matchingArchetypes: ['댄디 포멀', '글램 맥시멀', '모던 클래식'] },
  { id: '98', name: '호캉스', icon: '🏨', category: '나이트/특별', matchingArchetypes: ['코지 무드', '글램 맥시멀', '미니멀 시크걸'] },
  { id: '99', name: '여행/당일치기', icon: '🚐', category: '나이트/특별', matchingArchetypes: ['릴렉스 캐주얼', '서프 캐주얼', '감성 내추럴'] },
  { id: '100', name: '놀이공원 야간', icon: '🎡', category: '나이트/특별', matchingArchetypes: ['스포티 프레시', '러블리 페미닌', '컬러팝 무드'] },
]
